print('enter the following detail:')
name=input('enter your name:')
age=input('enter your age:')
location=input('enter your location:')
print('hello ' +name+ ' you are ' +age+ ' years old and live in '  +location+ '.')
